# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAddGroup():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_add_group(self):
        # Test name: test_add_group
        # Step # | name | target | value
        # 1 | open | /addressbook/ |
        self.driver.get("http://localhost/addressbook/")
        # 2 | setWindowSize | Maximize |
        self.driver.maximize_window()
        # 3 | click | name=user |
        self.driver.find_element(By.NAME, "user").click()
        # 4 | type | name=user | admin
        self.driver.find_element(By.NAME, "user").send_keys("admin")
        # 5 | click | name=pass |
        self.driver.find_element(By.NAME, "pass").click()
        # 6 | type | name=pass | secret
        self.driver.find_element(By.NAME, "pass").send_keys("secret")
        # 7 | click | css=input:nth-child(7) |
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
        # 8 | click | linkText=groups |
        self.driver.find_element(By.LINK_TEXT, "groups").click()
        # 9 | click | name=new |
        self.driver.find_element(By.NAME, "new").click()
        # 10 | click | name=group_name |
        self.driver.find_element(By.NAME, "group_name").click()
        # 11 | type | name=group_name | FG
        self.driver.find_element(By.NAME, "group_name").send_keys("FG")
        # 12 | click | name=group_header |
        self.driver.find_element(By.NAME, "group_header").click()
        # 13 | type | name=group_header | FH
        self.driver.find_element(By.NAME, "group_header").send_keys("FH")
        # 14 | click | name=group_footer |
        self.driver.find_element(By.NAME, "group_footer").click()
        # 15 | type | name=group_footer | FF
        self.driver.find_element(By.NAME, "group_footer").send_keys("FF")
        # 16 | click | css=form:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(2)").click()
        # 17 | click | name=submit |
        self.driver.find_element(By.NAME, "submit").click()
        # 18 | click | linkText=group page |
        self.driver.find_element(By.LINK_TEXT, "group page").click()
        # 19 | click | linkText=Logout |
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
